### ISSUE TITLE
Installation:  MarkupSafe==0.23 required

### ISSUE THREAD

**Issue by Diwakar-Gupta** [revault/aquarium#31]
## Describe the bug

When i run `pip install -r requirements.txt`

MarkupSafe 2.1.1 is installed and this project is not working with this version, I got an error

`ImportError: cannot import name 'soft_unicode' from 'markupsafe'`

## Solution
This project works well with `MarkupSafe==0.23`
Mentioning this in `requirements.txt` will solve the problem.

**Comment by darosior** [comment]
I can't reproduce. I don't encounter this error. Yet:
```
$ pip list |grep Markup
MarkupSafe             2.1.1
```
